{% set name = "scmdata" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfbf9af2cf8caf78c51248f7ba5cd9cf5e778900d2ec1cd6a70657ef3e6443dd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas
    - pint
    - python-dateutil

test:
  imports:
    - scmdata

  commands:
    python -c "import scmdata; assert scmdata.__version__ == '{{ version }}'"

about:
  home: https://github.com/lewisjared/scmdata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Handling of Simple Climate Model data
  doc_url: https://scmdata.readthedocs.io/en/latest/scmdata
  dev_url: https://github.com/lewisjared/scmdata

extra:
  recipe-maintainers:
    - znicholls
    - lewisjared
